In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [37]:
df = pd.read_csv("Churn_Modelling.csv")

In [38]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [39]:
df.drop(columns=["RowNumber", "CustomerId","Surname"], inplace=True)

In [40]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [42]:
df["Gender"] = LabelEncoder.fit_transform(LabelEncoder,df["Gender"])

In [43]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [44]:
df = pd.get_dummies(df,columns=["Geography"], dtype=int)

In [45]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1,0,0

In [46]:
x = df.drop(columns=["Exited"])
y = df["Exited"]

In [47]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [48]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [49]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [50]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [51]:
model = Sequential([
    Dense(64, activation="relu", input_shape = (x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1, activation="sigmoid")
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________

In [52]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy()

In [53]:
model.compile(optimizer=opt, loss= loss, metrics=["accuracy"])

In [54]:
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [55]:
callback = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

In [56]:
tf_callback = TensorBoard(log_dir, histogram_freq=1)

In [57]:
history = model.fit(x_train, y_train, epochs=100,
                    validation_data=(x_test,y_test),
                    callbacks = [tf_callback, callback])

Epoch 1/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4090 - accuracy: 0.8281 - val_loss: 0.3642 - val_accuracy: 0.8500
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3564 - accuracy: 0.8531 - val_loss: 0.3425 - val_accuracy: 0.8615
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3484 - accuracy: 0.8581 - val_loss: 0.3552 - val_accuracy: 0.8550
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3428 - accuracy: 0.8621 - val_loss: 0.3464 - val_accuracy: 0.8585
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3396 - accuracy: 0.8625 - val_loss: 0.3477 - val_accuracy: 0.8550
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8649 - val_loss: 0.3470 - val_accuracy: 0.8555
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3355 - accuracy: 0.8621 - val_loss: 0.3401 - val_accuracy: 0.8590
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3335 - accuracy: 0.8646 - val_loss: 0.3450 - val_accuracy: 0.8590
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3310 - accuracy: 0.8685 - val_loss: 0.3473 - val_accuracy: 0.8560
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8639 - val_loss: 0.3530 - val_accuracy: 0.8540
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3275 - accuracy: 0.8636 - val_loss: 0.3402 - val_accuracy: 0.8585
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3283 - accuracy: 0.8662 - val_loss: 0.3405 - val_accuracy: 0.8590
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3227 - accuracy: 0.8685 - val_loss: 0.3506 - val_accuracy: 0.8585
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3207 - accuracy: 0.8681 - val_loss: 0.3449 - val_accuracy: 0.8595
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3170 - accuracy: 0.8683 - val_loss: 0.3531 - val_accuracy: 0.8550
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3219 - accuracy: 0.8714 - val_loss: 0.3476 - val_accuracy: 0.8610
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3187 - accuracy: 0.8680 - val_loss: 0.3603 - val_accuracy: 0.8535

In [58]:
model.save("model.h5")

In [59]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [60]:
%tensorboard --logdir logs/fit20260618-205124

Reusing TensorBoard on port 6006 (pid 5136), started 0:02:03 ago. (Use '!kill 5136' to kill it.)