In [22]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [23]:
model = load_model("model.h5")

with open("scaler.pkl",'rb') as file:
    scaler = pickle.load(file)

In [30]:
input_data = {
    'CreditScore' :600,
    'Geography' :'France',	
    'Gender' :'Male',	
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,	
    'EstimatedSalary': 50000
}

In [31]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [33]:
input_df["Geography"] = pd.Categorical(
    input_df["Geography"], 
    categories=["France", "Germany", "Spain"]
)
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [34]:
le = LabelEncoder()

le.fit(["Female", "Male"])

input_df["Gender"] = le.transform(input_df["Gender"])

In [35]:
input_df = pd.get_dummies(input_df,columns=["Geography"], dtype=int)

In [36]:
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                  0                0

[1 rows x 12 columns]

In [37]:
scaled_input = scaler.transform(input_df)

In [38]:
scaled_input

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [42]:
predict_prob = model.predict(scaled_input)
predict_prob

1/1 [==============================] - 0s 16ms/step

array([[0.03955044]], dtype=float32)

In [43]:
if predict_prob>0.5:
    print('The customer is likely to churn')
else:
    print('The customer is not likely to churn')

The customer is not likely to churn